# Generated by Django 4.2.7 on 2025-02-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_banktransfer_options_alter_crypwallets_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={'verbose_name': '3-Manage Transfer', 'verbose_name_plural': '3-Manage Transfers'},
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='approval_document',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='fee_receipt',
        ),
    ]
